"""LangGraph state definition for the research agent."""

from __future__ import annotations

import operator
from dataclasses import dataclass, field
from typing import Annotated, TypedDict


@dataclass
class SubQuery:
    """A sub-query generated by the planner."""

    query: str
    source_type: str  # "academic", "news", "reference", "general"
    rationale: str = ""


@dataclass
class RetrievedDocument:
    """A document retrieved by a worker."""

    title: str
    content: str
    source: str  # URL or identifier
    source_type: str
    snippet: str = ""
    credibility_score: float = 0.5
    metadata: dict = field(default_factory=dict)


@dataclass
class Conflict:
    """A detected conflict between sources."""

    claim_a: str
    source_a: str
    claim_b: str
    source_b: str
    description: str
    resolution: str = ""


@dataclass
class SourceMeta:
    """Metadata about a source for credibility tracking."""

    url: str
    title: str
    source_type: str
    credibility_score: float = 0.5


@dataclass
class Critique:
    """Self-critique result from the critic node."""

    needs_refinement: bool
    overall_score: float  # 0.0 - 1.0
    gaps: list[str] = field(default_factory=list)
    diversity_issues: list[str] = field(default_factory=list)
    outdated_concerns: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    summary: str = ""


class ResearchState(TypedDict, total=False):
    """
    The central state for the research agent graph.

    Uses Annotated reducers so parallel worker nodes can append
    documents concurrently without overwriting each other.
    """

    # Input
    query: str
    task_id: str
    thread_id: str
    thread_item_id: str

    # Planning
    plan: list[SubQuery]

    # Retrieval (append-only via reducer)
    documents: Annotated[list[RetrievedDocument], operator.add]

    # Synthesis
    draft: str
    conflicts: list[Conflict]
    sources_metadata: list[SourceMeta]

    # Critique loop
    critique: Critique | None
    iteration: int
    max_iterations: int

    # Final output
    final_report: str

    # Streaming callback (not persisted)
    _send_event: object  # callable, excluded from serialization
